// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-__lCLleX2fo80PFVdc5FMxjhR9qqf80',
    appId: '1:981454566644:web:9ad92f47dbfe23faa41aa1',
    messagingSenderId: '981454566644',
    projectId: 'attendiq-b3f1c',
    authDomain: 'attendiq-b3f1c.firebaseapp.com',
    storageBucket: 'attendiq-b3f1c.firebasestorage.app',
    measurementId: 'G-PVLN30F8D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeLLb-awRCOEYDrOY24Oo07e03cqTo10o',
    appId: '1:981454566644:android:c361541c6b59edcca41aa1',
    messagingSenderId: '981454566644',
    projectId: 'attendiq-b3f1c',
    storageBucket: 'attendiq-b3f1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjpp6W-hDZIxMOUKy9oZA-kJ3AFcCHXt4',
    appId: '1:981454566644:ios:3bc9a94698470203a41aa1',
    messagingSenderId: '981454566644',
    projectId: 'attendiq-b3f1c',
    storageBucket: 'attendiq-b3f1c.firebasestorage.app',
    iosBundleId: 'com.ramsa.attendiq.attendIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjpp6W-hDZIxMOUKy9oZA-kJ3AFcCHXt4',
    appId: '1:981454566644:ios:3bc9a94698470203a41aa1',
    messagingSenderId: '981454566644',
    projectId: 'attendiq-b3f1c',
    storageBucket: 'attendiq-b3f1c.firebasestorage.app',
    iosBundleId: 'com.ramsa.attendiq.attendIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-__lCLleX2fo80PFVdc5FMxjhR9qqf80',
    appId: '1:981454566644:web:778ecffe5b2c3a7ba41aa1',
    messagingSenderId: '981454566644',
    projectId: 'attendiq-b3f1c',
    authDomain: 'attendiq-b3f1c.firebaseapp.com',
    storageBucket: 'attendiq-b3f1c.firebasestorage.app',
    measurementId: 'G-D4HFBBSVNV',
  );
}
